<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {   
        // Product::create(['name'=>'ISO Whey Clear','price'=>2500,'image'=>'images\Products\ISO Whey Clear.jpg','description'=>'Clear Whey is not just another protein shake. We’ve taken high-quality hydrolysed whey protein isolate and created a light and refreshing alternative — that’s more like juice than a milky protein shake.','type'=>'nutrition']);
        // Product::create(['name'=>'Cellutor','price'=>3000,'image'=>'images\Products\Cellutor.png','description'=>'COR-Performance Whey Isolate Protein Powder is an optimal source of protein when you’re looking to maintain lean muscle, replenish nutrients after a workout, and indulge your sweet tooth guilt-free.Every two scoops of COR-Performance Whey Isolate Protein Powder is packed with 24g of fast-acting whey protein and digestive enzymes so that you can satisfy your protein needs anytime of the day.','type'=>'nutrition']);
        // Product::create(['name'=>'Grass-Fed Whey Protein Isolate','price'=>2500,'image'=>'images\Products\Grass-Fed.webp','description'=>'Made from naturally fed, hormone-free cow whey and clean of artificial sweeteners, food dyes, gluten, and preservatives, Transparent Labs 100% Grass-Fed Whey Protein Isolate is one of the cleanest proteins on the market. It’s perfect for post-workout recovery and hitting daily protein goals.','type'=>'nutrition']);
        // Product::create(['name'=>'Fast&Up Pre Workout','price'=>1500,'image'=>'images\Products\Fast&Up.webp','description'=>'Extreme Mental FocusIntense Energy Blast.High Octane Power Output with Explosive Energy Blend.Refreshing Watermelon Flavour, Banned Substance Free.How To Use - Mix one scoop in 1000 ml water. Consume 20-30 minutes before training','type'=>'nutrition']);
        // Product::create(['name'=>'Kapiva Vegan Protein','price'=>1600,'image'=>'images\Products\Vegan Protein.webp','description'=>'Kapiva Vegan Protein- Chocolate is a healthy mix of nutrients with 26g of protein, 4.97g BCAAs, 4.54g Glutamic Acid and 26 Vitamins & Minerals. This is a great option for enhancing protein in vegetarian diets which are often low in protein. It also helps you recover quickly after a workout and supports the process of muscle building.','type'=>'nutrition']);
        // Product::create(['name'=>'GNC Pro Performance 100% Whey Protein ','price'=>3200,'image'=>'images\Products\Pro Whey.webp','description'=>'GNC Pro Performance Whey Protein 2 kg Chocolate Supreme comes loaded with 100% whey protein to help you fulfill your daily protein requirement. With GNC Whey Protein, you get 24g of protein per 36g serving which helps fuel your muscles and assists in speedy recovery. GNC Pro Performance Chocolate Supreme comes fortified with 100% whey protein (whey concentrate and whey isolate) which caters the protein requirement essential for bodybuilders, fitness enthusiasts while catering general protein requirement of individuals as well.','type'=>'nutrition']);
        // Product::create(['name'=>'GNC Total Lean Shake 25','price'=>1800,'image'=>'images\Products\Lean Shake.webp','description'=>'Meal Replacer is a substitute to your meal which is usually low in carbs, calories, high in fibre and meets your daily 1/3rd essential vitamin and mineral requirement. Meal replacements are designed for a wide variety of diets, each with its own specific needs. A. Protein is the satiating nutrient and whey protein is the best. Meal replacements are also a convenient and effective way to exercise portion control, an essential component of a successful weight management plan.','type'=>'nutrition']);
        // Product::create(['name'=>'FINAFLEX Clear Protein','price'=>3000,'image'=>'images\Products\FinaFlex.jpg','description'=>'CLEAR PROTEIN delivers 25 Grams of the highest quality protein available in each serving, featuring Whey Protein Hydrolysate (Hydrolyzed Whey), regarded as the premier form of whey protein on the market. Using instantized proteins virtually guarantees a smooth, full-bodied milkshake-like consistency each and every time CLEAR PROTEIN is mixed in just 6-8 ounces of water or other beverage.','type'=>'nutrition']);
        // Product::create(['name'=>'BLESSED Plant-Based Protein','price'=>3200,'image'=>'images\Products\Blessed.jpg Protein.webp','description'=>'Blessed Protein is an all-natural and vegan-friendly pure golden pea protein isolate that contains 23g of protein per scoop and all of the essential amino acidsat only 4g of net carbs. This means Blessed will keep you fuller for longer without any bloating. No need to stress out about your daily protein intake with Blessed Protein.','type'=>'nutrition']);
        // Product::create(['name'=>' MyProtein','price'=>2600,'image'=>'images\Products\Myprotein.jpg','description'=>' MyProtein is an extremely rich source of whey isolate, having undergone an expert purifying process to ensure maximum protein integrity, and deliver 90% protein and just 1% fat.','type'=>'nutrition']);
        // Product::create(['name'=>'HD Essential Protein Powder (Sweet Vanilla Flavor)','price'=>2500,'image'=>'images\Products\Halleljuah Diet.jpg','description'=>'Organic Essential Protein Sweet Vanilla Flavor is ideal for anyone with an active, outdoors, stay-fit lifestyle. Organic Essential Protein Sweet Vanilla Flavor will help you maintain a lean body, build strong healthy bones, and strengthen your immune system.* Worry free, delicious, and good for you.','type'=>'nutrition']);


        // Product::create(['name'=>'MAXPRO PTM405M 2HP(4 HP Peak) Multifunction Folding Treadmill','price'=>30000,'image'=>'images\Products\Maxpro Treadmill.jpg','description'=>'2.0 HP(4 HP Peak) DC quite motor deliver power for interval, speed, or endurance training. Speed: 1 to 14 km/hr Speed levels available, you can select different speed base on your physical condition and exercise based.Warranty Details : 1 Year Motor Warranty, 1 Year Part Warranty, Life time Frame Warranty.','type'=>'gym equipment']);
        // Product::create(['name'=>'Life Fitness Weight Station G4','price'=>28000,'image'=>'images\Products\Fitness Weight Station G4.png','description'=>'The Life Fitness Weight Station G4 offers an even wider selection of exercises for training the entire body so you never get bored during workouts. Experience additional exercises that challenge your muscles in completely new ways. The adjustable training bench, the comfortable back rest and chest support and the different grip positions of the Life Fitness Kraftstation GS4 offer a high degree of comfort and ergonomics.','type'=>'gym equipment']);
        // Product::create(['name'=>'Olympic Incline Bench','price'=>18000,'image'=>'images\Products\Olympic Incline Bench.jpg','description'=>'Designed as per the international standards of power lifting. Ten-inch bench width allows free shoulder movement during bench press. Forty-eight inch bench length allows full stretch of the users body. Two positions replaceable bar hold assembly with heavy-duty stainless steel plate for durability. 30 degree inclined backrest for optimum exercise benefit. Heavy duty platform provided for the spotter.','type'=>'gym equipment']);
        // Product::create(['name'=>'StarX 10 Kg Home Gym Exercise Set','price'=>2000,'image'=>'images\Products\StarX 10KG GYM set.jpg','description'=>'This set of adjustable PVC dumbbells is an excellent choice for a home gym. This take seconds to assemble and take out. Compact, convenient, and easy to use and store. All-for-one dumbbells eliminate the need for multiple dumbbells in your workout space.','type'=>'gym equipment']);
        // Product::create(['name'=>'WELCARE Multi Adjustable Weight Bench','price'=>8000,'image'=>'images\Products\WELCARE Multi weight bench.jpg','description'=>'8 backrest positions get you to hit specific muscles you need. This versatile bench can be adjusted to Incline, Decline and Flat Weight Bench and thus can be used to exercise different muscle groups such as the chest, shoulders, core and lower body, so you can have balanced muscle development.','type'=>'gym equipment']);
        // Product::create(['name'=>'Infinity Bench','price'=>20000,'image'=>'images\Products\Infinity Bench.jpg','description'=>'20 in 1 Bench It can be used (Flat /Incline/Decline/ / Lag Curl/Leg Extension/ Lat pull Down /Ground Pulley/Arm Curl / Chest press / Butterfly/Dips/Twister) , If you want the ability to perform all the basic barbell and dumbbell exercises then this bench should be your choice & Will Fulfill Your Fitness Requirements. A Combination of all gym Equipment for the Perfect Workout , It is Highly Durable and Long Lasting , A Perfect Muscle Builder In-Box Cont','type'=>'gym equipment']);
        // Product::create(['name'=>'Kamachi B-003 Adjustable Weight Lifting Multi-Function Machine','price'=>10000,'image'=>'images\Products\Kamacchi B-0003 Weight Incline Bench.jpg','description'=>'It Is Made Of Heavy Duty Steel It Provides Stability And Safety For Simple Exercise This Weight Bench Will Meet Most Peoples Exercise Needs. Max. Weight Capacity: 150 Kgs','type'=>'gym equipment']);
        // Product::create(['name'=>'Dolphy Foldable Sit Up Bench for Home Gym Abs Exercises','price'=>7000,'image'=>'images\Products\Dolphy Foldable Sit Uo Bench.jpg','description'=>'Sit-up Bench Adjustable Benches Sit-ups plate board Supine boards Fitness Equipment Multi functional abdomen back devices Household Light weight Strength Training Equipment Core Abdominal Trainers Standard Weight Training Benches ','type'=>'gym equipment']);
        // Product::create(['name'=>'Lifeline LIT1 Steel Home Gym with Tummy Trimmer','price'=>17000,'image'=>'images\Products\Lifeline LIT1 Stell Gym set.jpg','description'=>'Multiple exercise functions: Chest extension, high pull, low pull, rowing, peck-deck, leg extension.Easy to use, space saving, no-cable-change design, total body conditioning and superior endurance with more than 18 exercise options ','type'=>'gym equipment']);



        // Product::create(['name'=>'Leather Combo of FCB Bag Fitness Accessories Gym Kit','price'=>700,'image'=>'images\Products\a1.jpg','description'=>' It Is Useful As Gym Bag, Small Travel Bag, Swimming Bag.The Bag Comes In A Material Which Is Specially Chosen For Gym Purpose with PU-Leather Look And Is Long Lasting And Durable, You Can Use This Bag For Years And Will Be As Good As New. It Is Easy To Carry And Looks Very Elegant And Stylish, It Is One Stylish Companion For Your Everyday Visit To The Gym. It Is Suited For Men As Well As Women And Will Look Very Stylish With Your Gym Wear. The Bag Has A Compartment Deep Enough For You To Store Your Essential Items And Wide Enough Too','type'=>'gym accessories']);
        // Product::create(['name'=>'Strauss Adjustable Weight Lifting Strap with Palm Protecting Grip','price'=>300,'image'=>'public\images\Products\a2.jpg','description'=>'Strauss offers the most advanced scientifically developed accessory, designed for superior lifters, unique three in one product protects hands like a glove, and functions as lifting grip, wrist wrap combination. Textured gel neoprene grip straps combined with padded, adjustable wrist support for extra comfort.','type'=>'gym accessories']);
        // Product::create(['name'=>'Nivia 11041 Cotton Thumb Wrist Support','price'=>200,'image'=>'images\Products\a4.jpg','description'=>'High elasticity polyester material to allow for either a loose or snugger fit without cutting off circulation and permeability is strong.Thumb loop makes wrap around easy to put on and take off.','type'=>'gym accessories']);
        // Product::create(['name'=>'Sfane Gray & Black Leather Duffel Gym Bag','price'=>320,'image'=>'images\Products\a5.jpg','description'=>'Sfane Sports Bag practical everyday sizing make it great for hauling just about anything.Big compartment holds Sports Clothing, Gloves, Shaker, Sports ball, Sports Accessories, etc. Or anything that might be wet or soiled. High quality provide years of dependable service. Made in India..','type'=>'gym accessories']);
        // Product::create(['name'=>'Kobo WTA-04 Power Cotton Gym Support','price'=>300,'image'=>'images\Products\a6.jpg','description'=>'Thumb loops with extra length strap to ensure shifting does not occur when in use.Constructed from a heavy blend cotton-eglantine for maximum support.The wrist wraps use stretch fabrics to provide a great fit that can stand the wear and tear of a heavy workout.','type'=>'gym accessories']);
        // Product::create(['name'=>'Kobo Leather Fitness Gloves','price'=>340,'image'=>'images\Products\a7.jpg','description'=>'Leather front palm .Padded front palm.Soft material back hand for sweat ventilation.perfect for weight lifting.','type'=>'gym accessories']);
        // Product::create(['name'=>'Fitkit Classic Bottle Shaker 700ml','price'=>180,'image'=>'images\Products\a8.jpg','description'=>'Our advance design let you open the lid with just a simple push of the bottom.You can open and drink with one hand, let you stay hydrated while performing other actions.The mixer ball wire whisk— add your ingredients, drop in the FITKIT classic protein shaker mixer sports bottle, and shake','type'=>'gym accessories']);
        // Product::create(['name'=>'Aprodo Weight Lifting Gym Belt','price'=>500,'image'=>'images\Products\a9.jpg','description'=>'APRODO Weight Lifting Belt are ergonomically designed to provide Firm & Comfortable Lumbar Support during any kind of Strength Training','type'=>'gym accessories']);
        // Product::create(['name'=>'GOCART Tactical Gloves Military Army Shooting Gym & Fitness Gloves','price'=>500,'image'=>'images\Products\a11.jpg','description'=>'Comfortable,Breathable Design .The high-quality Nylon fabric we use is not only elastic,, high-performance Microfiber material, The knuckle part of our tactical gloves, The palm part of our tactical gloves, with wear-resistant PU liner, Nicely stitched, careful sewing breathable material and adjustable wrist design provide sense of snug and support Tactical Gloves are the perfect fit for professionals and athletes looking to increase the productivity of their training','type'=>'gym accessories']);
        // Product::create(['name'=>'Izoo Latex Gym Ball','price'=>700,'image'=>'images\Products\a12.jpg','description'=>'This Izoo anti-burst ball is soft, supple, and recommended by physical therapists for rehabilitation of problem areas such as back, knees, and shoulders. Great for yoga workouts, sit up, abdominal exercises and stretching after a hard cardio or bodybuilding workout routine. ','type'=>'gym accessories']);


        // Product::create(['name'=>'Pro Gym Mens Slim Fit T-Shirt','price'=>400,'image'=>'images\Products\t1.jpg','description'=>'Shop from a wide range of T-Shirt from Pro Gym. Perfect for your everyday use, you could pair it with a stylish pair of Jeans or Trousers complete the look.','type'=>'gym clothing']);
        // Product::create(['name'=>'SportSoul Nylon Gym T-shirt for Men ','price'=>430,'image'=>'images\Products\t2.jpg','description'=>'SportSoul Compression Wear is a must-have whether you are a professional athlete looking to improve performance, a fitness enthusiast or just someone looking to stay fit and active','type'=>'gym clothing']);
        // Product::create(['name'=>'ReDesign Apparels Nylon Redesign Compression Top Full Sleeve Tights T-Shirt','price'=>999,'image'=>'images\Products\t3.jpg','description'=>'Redesign is most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles and reduces blood lactate build up, to enhance performance and speed up recovery time. Redesign compression top increases circulation and reduces fatigue, also risk of injury ,so you can go harder for longer. Perfect for any kind of sport.','type'=>'gym clothing']);
        // Product::create(['name'=>'Compression Mens Slim Fit T-Shirt','price'=>400,'image'=>'images\Products\t4.jpg','description'=>'Shop from a wide range of Compression T-Shirt from Pro Gym. Perfect for your everyday use, you could pair it with a stylish pair of Jeans or Trousers complete the look.','type'=>'gym clothing']);
        // Product::create(['name'=>'Inkast Denim Jogger','price'=>800,'image'=>'images\Products\j1.jpg','description'=>'Inkast Denim Co. offers a mix of classic as well as contemporary denim styles in a variety of washes. Designed for all casual occasions, Inkast offers the authentic denim look with high emphasis on quality, craftsmanship and fit.','type'=>'gym clothing']);
        // Product::create(['name'=>'Peppyzone Mens Slim Fit Trackpants','price'=>600,'image'=>'images\Products\j2.jpg','description'=>'Shop from a wide range of Trackpants from Peppyzone. Perfect for your everyday use you could pair it with a stylish t-shirt or shirt to complete the look.','type'=>'gym clothing']);
        // Product::create(['name'=>'Gristones men Jogger','price'=>700,'image'=>'images\Products\j3.jpg','description'=>'Shop from a wide range of Trackpants from GRITSTONES. Perfect for your everyday use you could pair it with a stylish t-shirt or shirt to complete the look.','type'=>'gym clothing']);
        // Product::create(['name'=>'Mena Regular Jogger','price'=>500,'image'=>'images\Products\j4.jpg','description'=>'Shop from a wide range of Trackpants. Perfect for your everyday use you could pair it with a stylish t-shirt or shirt to complete the look.','type'=>'gym clothing']);
        // Product::create(['name'=>'Reguks Mens Shorts','price'=>400,'image'=>'images\Products\s1.jpg','description'=>'Casual Trousers made from 100% rich combed cotton, giving it a rich look, perfect fit ,Skin friendly fabric for comfort of wearing, itch-free waistband . Deep side pockets on both sides , one pocket with zipper and for better customer needs. Biowashed fabric for adding smooth and more quality to product','type'=>'gym clothing']);
        // Product::create(['name'=>'Polyster Shorts','price'=>450,'image'=>'images\Products\s2.jpg','description'=>'Casual Trousers made from rich polyster, giving it a rich look, perfect fit ,Skin friendly fabric for comfort of wearing, itch-free waistband . Deep side pockets on both sides , one pocket with zipper and for better customer needs. Biowashed fabric for adding smooth and more quality to product','type'=>'gym clothing']);
        // Product::create(['name'=>'Cotton Blend Shorts','price'=>550,'image'=>'images\Products\s3.jpg','description'=>'Casual Trousers made from 100% rich combed cotton, giving it a rich look, perfect fit ,Skin friendly fabric for comfort of wearing, itch-free waistband . Deep side pockets on both sides , one pocket with zipper and for better customer needs. Biowashed fabric for adding smooth and more quality to product','type'=>'gym clothing']);
        // Product::create(['name'=>'Cotton Blend Shorts','price'=>590,'image'=>'images\Products\s4.jpg','description'=>'Casual Trousers made from 100% rich combed cotton, giving it a rich look, perfect fit ,Skin friendly fabric for comfort of wearing, itch-free waistband . Deep side pockets on both sides , one pocket with zipper and for better customer needs. Biowashed fabric for adding smooth and more quality to product','type'=>'gym clothing']);




    }
}
